# Generated by Django 2.2.10 on 2020-10-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget_app', '0002_auto_20201018_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='monthcategory',
            options={'verbose_name_plural': 'Month categories'},
        ),
        migrations.AlterField(
            model_name='monthcategory',
            name='category_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
